---
#Allgemeine Einstellungen

#Commands & Funktionen
AntiXray: false
BoosterCommand: true
StarterKit: true

#Neue Items & Blöcke 1.16 ALPHA Kann Fehler enthalten da dies auserhalb der BlockID : 255 ist
NewItems: true #Setze es auf false um es zu deaktivieren

#ItemDisplay
inames: true #aktiviere/deaktiviere die ItemNamen

#Blitze beim Join
blitze: true #aktiviere/deaktiviere Blitze beim Joinen des Servers
sound: true #aktiviere/deaktiviere den Donner

#NetzwerkName
networkname: "§f[§eCore§4V5§f] §eALPHA" #schreibe hier dein servername oder was frag mich rein...

#EconomySystem
DefaultMoney: 1000

#Weitere Einstellungen
defaultspawn: true
rejoinallowed: true #möchtest du das die Spieler automatich rejoinen?
rejoinserverip: 127.0.0.1
rejoinserverport: 19132
maxhomes: 10 #Setze ein Limit für Homes
collision: true #aktiviere/deaktiviere collision/schubsen
serverversion: pocketmine #nutze altay oder pocketmine um zwichen den verschiedenen versionen zu wechseln
keepinventory: false #setze auf true um dein Inventar zu Behalten
PingLimit: 30000 #Setze das Maximale Pinglimit ein

#Regelwerk
Regeln: false #Entscheide selber ob du die Regeln nutzten willst oder nicht...

#HubCommand
Defaultworld: world #Setze hier die Defaultwelt
Gamemode: 2 #setze hier den Gamemode für die Welt
Food: true #Aktivier/Deaktivier das Auffüllen des Hungers
Heal: true #Aktivier/Deaktivier das Auffüllen des Lebens
Teleportsound: true #Aktivier/Deaktivier den Teleportsound

#LiftSystem
helferprivatliftuse: true
helperprivateLift: true
checkFloor: true

#Statstext
statstext: false
X: 0
Y: 0
Z: 0
level: world
...