---
#DiscordEinstellungen

#Möchtest du MCPE to Discord funktion Aktivieren?
DC: true #setze auf true um es zu aktivieren

dclink: "Discord-Link"
chatname: "CoreV5"
webhookurl: "https://discord.com/api/webhooks/786652779191861308/bl21p4_fQR_HBZs6uudlC9qsL7M7Gz8zMuKfWI080vBnB-POUrv8BTQUuJFs8B3AY7to" #füge hier deine Webhockurl ein
webhookdc: "https://discordapp.com/api/webhooks/"
webhookname: "CoreV5"
...